name = "mocaton"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
MINI_APP_URL = "https://mocaton.pages.dev"
BOT_USERNAME = "mocatonbot"
