// contract/scripts/deploy.ts
import { TonClient, WalletContractV4, toNano } from '@ton/ton';
import { mnemonicToPrivateKey } from '@ton/crypto';
import { StakingPool } from '../build/StakingPool'; // Generated by Tact compiler

async function deploy(network: 'testnet' | 'mainnet') {
  const endpoint = network === 'testnet'
    ? 'https://testnet.toncenter.com/api/v2/jsonRPC'
    : 'https://toncenter.com/api/v2/jsonRPC';

  const client = new TonClient({ endpoint });

  // Load mnemonic dari env
  const mnemonic = process.env.TON_ADMIN_MNEMONIC?.split(' ');
  if (!mnemonic) throw new Error('TON_ADMIN_MNEMONIC not set');

  const keyPair = await mnemonicToPrivateKey(mnemonic);
  const wallet = WalletContractV4.create({
    publicKey: keyPair.publicKey,
    workchain: 0,
  });

  const walletContract = client.open(wallet);
  const adminAddress = wallet.address;

  console.log(`Deploying to ${network}...`);
  console.log(`Admin address: ${adminAddress.toString()}`);

  // Init contract
  const contract = StakingPool.fromInit(adminAddress);
  const contractAddress = contract.address;
  console.log(`Contract will be deployed at: ${contractAddress.toString()}`);

  const isDeployed = await client.isContractDeployed(contractAddress);
  if (isDeployed) {
    console.log('Contract already deployed!');
    return;
  }

  // Deploy
  const seqno = await walletContract.getSeqno();
  await walletContract.sendTransfer({
    seqno,
    secretKey: keyPair.secretKey,
    messages: [
      {
        to: contractAddress,
        value: toNano('0.5'), // Initial balance untuk gas
        init: contract.init,
        body: '',
      }
    ],
  });

  console.log('✅ Contract deployed!');
  console.log(`Address: ${contractAddress.toString()}`);
  console.log('\nSimpan address ini ke environment variable TON_CONTRACT_ADDRESS');
}

const network = (process.argv[2] as 'testnet' | 'mainnet') || 'testnet';
deploy(network).catch(console.error);
